- name: playbook to install SMS News Service
  hosts: all
  serial: 1
  vars:
    local_path: /home/{{ ansible_ssh_user }}
    anaconda_path: "{{ local_path }}/{{ anacondadir }}"
    default_backend_path: "{{ backend_location }}/news-backend"
    conda: "{{ anaconda_path }}/bin/conda"
    env_path: "{{ anaconda_path }}/envs/{{ backend_env }}/bin"
    python: "{{ anaconda_path }}/envs/{{ backend_env }}/bin/python"
  tasks:

    - include: backend_path.yaml
      tags: [always]

    - include: clone.yaml
      tags: [install]

    - include: mongo.yaml
      tags: [install]
      when: inventory_hostname in groups['db']


    - include: conda.yaml
      tags: [install]
      when: >
        inventory_hostname in groups['db'] or
        inventory_hostname in groups['news']

    - include: newsdb.yaml
      tags: [install]
      when: >
        inventory_hostname in groups['db'] or
        inventory_hostname in groups['news']

    - name: install nginx, python-httplib2
      tags: [install]
      apt:
        name: "{{ item }}"
        state: present
        force: yes
      become: true
      with_items:
        - nginx
        - python-httplib2
      when: >
        inventory_hostname in groups['news']

    - name: copy news config file
      tags: [install]
      when: inventory_hostname in groups['news']
      template: src={{ inventory_dir }}/config-news.py.j2 dest={{ backend_path }}/news-service/config.py

    - include: serve_db.yaml
      when: inventory_hostname in groups['db']
      tags: [serve]

    - include: serve_app.yaml
      when: inventory_hostname in groups['news']
      tags: [serve]
      vars:
        app_path: "{{ backend_path }}/news-service"
